### ISSUE TITLE
Filter doesn't let anything through

### ISSUE THREAD

**Issue by jtiscione** [pste/node-red-filter#2]
Injecting JSON {"roses":"red", "violets":"blue"}, with property set to "payload.roses", and filter set to "red". Nothing gets through. I tried "roses" and "msg.payload.roses" instead of payload.roses, and ".*" instead of "red". Tried all kinds of things. Nothing gets through at all.

**Comment by pste** [comment]
tested, you're right. I'm working on a fix

**Comment by pste** [comment]
#4d9abb3 fixed
